server:
  port: 9091
spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mukeshsilwal/configserver1.git
          clone-on-start: true


eureka:
  client:
    register-with-eureka=true: true